name: Codecov
on:
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    name: Generate badge
    steps:
      - uses: actions/checkout@v3
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aimeudoxie/My_brandAPI
